### ISSUE TITLE
Design improvement

### ISSUE THREAD

**Issue by cnico** [samlich/peertube-plugin-chapters#10]
Hi, 

This plugin is really useful, thanks for it.

I wanted to suggest you to improve its design / user interaction because it is a bit disturbing for lambda users.
In my usage, we have french (long) names for the chapters.

The list of chapters should preferably display bottom and not on the video.
The list of chapters could be larger so that long names display correctly. I think it should be twice larger.
With mouse over the chapter button, the list appears but we can not select a chapter as the list disappear when you move the mouse up. We have to click on the chapter button to be able to select a chapter. 
I suspect there are technical reasons for it so I suggest this behavior : when mouse is over the chapter button, only the current chapter name could be displayed and when you clic the chapter bouton, you can choose another chapter.

Regards,

**Comment by samlich** [comment]
Thanks for the suggestions, and sorry for my late reply. The chapter list is added with the builtin ChaptersButton in Video.js. I'm not sure why it behaves that way, as the other menus don't seem to do that, and [this demo](https://www.nuevodevel.com/nuevo/showcase/chapters) doesn't show the menu on mouseover either (although that may be a change made by the plugin being advertised). Not sure how to change that.

This plugin will be [obsoleted in PeerTube's 2023 roadmap](https://github.com/Chocobozzz/PeerTube/issues/271#issuecomment-1451968990) , so I don't want to make "big" feature changes like adding a list below the video, but you could keep an eye on that link to give them any suggestions.

I've added a [commit](https://github.com/samlich/peertube-plugin-chapters/commit/3dee61dc3d8780138e26e766bfebd9bfcb218d97) to make the list larger and left-align the text. I'll close this issue once a new release is pushed.

**Comment by samlich** [comment]
New version has been released with the layout fixes.

**Comment by cnico** [comment]
Thanks, I will test it.
