### ISSUE TITLE
Does it work in Peertube 5.1?

### ISSUE THREAD

**Issue by ghost** [samlich/peertube-plugin-chapters#11]
Hi,

I am not able to use the plugin in Peertube 5.1. Although it says that it is installed correctly, then there is no "Plugin settings" tab when editing a sample video. ¿Is it because of the version or I am doing something wrong?

![image](https://user-images.githubusercontent.com/116880734/236808703-2c8811a7-0f50-4151-8c9e-cf6c04f1ea72.png)

Thank you!

Mikel

**Comment by metxeberriabirt** [comment]
It appeared after a restart of the dockers.
