### ISSUE TITLE
Thumbnails for chapters

### ISSUE THREAD

**Issue by B0pol** [samlich/peertube-plugin-chapters#6]
It would be nice to have thumbnails for chapters so that users can preview.
Example with YouTube: 
![image](https://user-images.githubusercontent.com/58657617/141643931-e33511eb-41d7-4d78-86bf-d326e1217358.png)
YouTube takes a screenshot of the starting time.

**Comment by samlich** [comment]
This will require https://github.com/Chocobozzz/PeerTube/pull/2315 and maybe some more changes. I'll try to look into it when finishing #7, not sure how much effort is needed. Will require PeerTube release after merged, so I'll publish a version with #7 first.

**Comment by samlich** [comment]
Closing as chapters are now on the PeerTube 2023 roadmap https://joinpeertube.org/news/roadmap-v6
