### ISSUE TITLE
Non-Latin titles are always displayed in the lower case

### ISSUE THREAD

**Issue by quicktrick** [samlich/peertube-plugin-chapters#8]
For example, chapter titles written in Cyrillic are always displayed in the lower case, regardless of their true case. This happens in both plain text and Markdown.

The original chapters:

```
01:01 Немухин В.Н.
02:52 Зверев А.Т.
04:23 Шемякин М.М.
05:07 Яковлев В.И.
06:00 Сидур В.А.
06:46 Врубель Д. и Тимофеева В.
07:18 Зиновьева Т.А.
07:59 Кропивницкий Е.Л.
08:28 Чубаров Е.И.
09:07 Кузнецова В.Г.
09:36 Гинзбург Е.М.
10:16 Воронова Л.
```

And this is what is displayed:

![image](https://user-images.githubusercontent.com/18548503/162620462-ef48ffa9-577a-418f-a812-68e8fbed89e0.png)

**Comment by samlich** [comment]
I can't reproduce. Can you link me to an example? If you edit the video, is the capitalization correct in the edit box?

I can check this myself, if I can access the video and it's not a browser-specific issue, but if you do inspect element, could you check what it looks like in the HTML. Right-clicking won't really work, but if you open the dev tools (ctrl-shift-i) and click the select element button (or ctrl-shift-c), then you can click on the text. It should have `<span class="vjs-menu-item-text">Немухин В.Н.</span>`.

**Comment by quicktrick** [comment]
Thanks for your reply, @samlich!  I'm sorry, I coudn't find the code you mentioned.  You can see it yourself in any video on my server, for example, [here](https://tube.artsale.info/w/2DAgjSVQmAYqsjYmF2JFaY). Just in case: the server runs on FreeBSD.

Here is the screenshot of the edit box:
![image](https://user-images.githubusercontent.com/18548503/166092896-5d1d55c9-e7e3-4e57-ae45-7b41b7a9ccd6.png)

Here is the menu:
![image](https://user-images.githubusercontent.com/18548503/166093410-e7a7061f-1c3a-49f3-817b-c1eef4e1ac47.png)

Edit:
I found it. The HTML has the correct case: `<span class="vjs-menu-item-text">Зверев&nbsp;А.Т.</span>`. The browser is Chrome version 101.0.4951.41 (Official Build) (64-bit).  But I can see the same issues in Firefox and Opera.  And the same is on my mobile phone, too.

**Comment by samlich** [comment]
Sorry for taking so long, should be fixed by the update now. It was due to a video.js update adding `text-transform: lowercase`, so the plugin now overrides that with `text-transform: none`.

**Comment by quicktrick** [comment]
Thank you very much, bro! I only just updated PeerTube from 4.2.0-rc.1 to 4.3.1. And I also updated your plugin. Everything is displayed correctly now! Thanks a lot again!
